- name: monit | Install monit
  yum: name={{item}} state=present
  with_items:
    - monit
- name: monit | Creates scripts directory
  file: path=/etc/monit/scripts state=directory
- name: monit | Creates conf.d directory
  file: path=/etc/monit/conf.d state=directory
