# vim: ft=ansible
---
- hosts: "{{ target }}"
  sudo: yes
  vars:
    target: 127.0.0.1
  tasks:
  - shell: iptables -I OUTPUT 1 -j ACCEPT
  - name: Java | Install base components
    yum: name={{item}} state=present
    with_items:
      - java-1.8.0-openjdk-devel
      - tmux
      - git
